# Generated by Django 4.1.3 on 2024-05-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.IntegerField(blank=True, max_length=15, null=True),
        ),
    ]
