# Generated by Django 4.1.3 on 2024-05-09 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
